/**
 * Zod schema for spec.json — the PM Agent's output.
 * This is the source of truth for the spec structure.
 * All other code that reads spec.json must validate through this schema.
 */

import { z } from 'zod'

export const FeatureSchema = z.object({
  id: z.string().describe('Unique feature ID, e.g. F001'),
  name: z.string().describe('Short feature name'),
  confidence: z.enum(['high', 'medium', 'low']).describe(
    'high = every similar app needs this, medium = most do, low = optional/complex',
  ),
  acceptance_criteria: z
    .array(z.string())
    .min(1)
    .describe('Concrete, testable criteria. Each item must be independently verifiable.'),
  out_of_scope: z
    .array(z.string())
    .optional()
    .describe('Explicitly excluded items to prevent scope creep'),
})

export const ConstraintsSchema = z.object({
  auth: z.boolean().describe('Does the app need user authentication?'),
  database: z.boolean().describe('Does the app need persistent data storage?'),
  file_upload: z.boolean().describe('Does the app need file upload capability?'),
  email: z.boolean().describe('Does the app need to send emails?'),
  payments: z.boolean().describe('Does the app need payment processing?'),
})

export const SpecSchema = z.object({
  id: z.string().describe('Unique spec ID, generated by PM Agent'),
  title: z.string().describe('Short app title, 2-5 words'),
  description: z.string().describe('One paragraph describing what the app does'),
  business_domain: z
    .string()
    .describe(
      'Identified business domain, e.g. expense-management, e-commerce, appointment-booking',
    ),
  features: z.array(FeatureSchema).min(1),
  constraints: ConstraintsSchema,
  clarifying_questions: z
    .array(z.string())
    .optional()
    .describe('Genuine ambiguities that need user input before building can start'),
})

export type Spec = z.infer<typeof SpecSchema>
export type Feature = z.infer<typeof FeatureSchema>
export type Constraints = z.infer<typeof ConstraintsSchema>
